(ns record-fixtures
  "Regenerate test/riff/fixtures.cljc from real WAV files produced by ffmpeg.

       nbb tools/record_fixtures.cljs

   The portable suite must assert conformance against real files on
   ClojureScript, where there is no shell and no filesystem, so short reference
   files are recorded here once and checked in as base64.

   Each file is confirmed readable by ffprobe before being written."
  (:require ["node:child_process" :as cp]
            ["node:fs" :as fs]
            [kotoba.lang.text :as str]))

(def ^:private cases
  ;; [name codec channels] — 0.05 s at 8 kHz keeps every file under 4 KB while
  ;; still carrying several hundred frames. ffmpeg writes s24/s32 as
  ;; WAVE_FORMAT_EXTENSIBLE, which is the point of including them.
  [["u8" "pcm_u8" 1]
   ["s16" "pcm_s16le" 2]
   ["s24" "pcm_s24le" 2]
   ["s32" "pcm_s32le" 2]
   ["f32" "pcm_f32le" 2]])

(defn- sh [cmd args]
  (let [r (cp/spawnSync cmd (clj->js args) #js {:encoding "buffer"})]
    (when-not (zero? (.-status r))
      (throw (ex-info (str cmd " failed") {:stderr (str (.-stderr r))})))
    r))

(defn- encode [codec channels path]
  (sh "ffmpeg" ["-hide_banner" "-v" "error" "-f" "lavfi"
                "-i" "sine=frequency=440:duration=0.05:sample_rate=8000"
                "-ac" (str channels) "-c:a" codec path "-y"])
  ;; the reference must accept its own output before we record it
  (sh "ffprobe" ["-hide_banner" "-v" "error" "-show_entries" "stream=codec_name" path])
  (vec (js/Array.from (fs/readFileSync path))))

(defn- b64 [bytes] (.toString (.from js/Buffer (clj->js bytes)) "base64"))

(defn -main []
  (let [recorded (mapv (fn [[name codec channels]]
                         [name (encode codec channels (str "/tmp/riff-fixture-" name ".wav"))])
                       cases)
        lines (concat
               ["(ns riff.fixtures"
                "  \"Real WAV files produced by ffmpeg, recorded so the portable suite can"
                "   assert conformance on both runtimes with no shell and no filesystem."
                ""
                "   0.05 s of a sine wave at 8 kHz per file. s24 and s32 are"
                "   WAVE_FORMAT_EXTENSIBLE, which is how ffmpeg writes those widths, and all"
                "   of them carry a LIST/INFO chunk the walker has to step over."
                ""
                "   Generated by tools/record_fixtures.cljs — do not hand-edit.\")"
                ""
                "(def files"
                "  {"]
               (mapcat (fn [[name bytes]]
                         [(str "   \"" name "\"")
                          (str "   \"" (b64 bytes) "\"")])
                       recorded)
               ["   })"])]
    (fs/writeFileSync "test/riff/fixtures.cljc" (str (str/join "\n" lines) "\n"))
    (println "wrote test/riff/fixtures.cljc"
             (str "(" (str/join ", " (map (fn [[n bs]] (str n " " (count bs) "B")) recorded)) ")"))))

(-main)
